spring:
  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: smtp.sina.com
    port: 25
    username: mygodness30@sina.com
    password: 
    properties: 
      # 是否使用ssl安全连接
      mail.smtp.ssl.enable: true
      # 邮件发送协议
      mail.transport.protocol: stmp
      # 邮件服务器地址
      mail.host: smtp.qq.com
      # 是否验证用户名,密码
      mail.smtp.auth: true