spring:
  freemarker:
    # 指定HttpServletRequest的属性是否可以覆盖controller的model的同名项
    allow-request-override: true
    # 指定HttpSession的属性是否可以覆盖controller的model的同名项
    allow-session-override: true
    # 是否开启template caching
    cache: false
    # 设定Template的编码
    charset: UTF-8
    # 是否检查templates路径是否存在
    check-template-location: false 
    # 设定Content-Type
    content-type: application/*
    # 是否允许mvc使用freemarker
    enabled: true
    # 设定所有request的属性在merge到模板的时候,是否要都添加到model中
    expose-request-attributes: true
    # 设定所有HttpSession的属性在merge到模板的时候,是否要都添加到model中
    expose-session-attributes: true
    # 设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
    expose-spring-macro-helpers: true
    # 是否优先从文件系统加载template,以支持热加载,默认为true
    prefer-file-system-access: true
    # 设定freemarker模板的前缀
    prefix: 
    # 设定freemarker模板后缀
    suffix: .ftl
    # 指定RequestContext属性的名
    request-context-attribute:
    # 设定模板的加载路径,多个以逗号分隔,默认: ["classpath:/templates/"]
    template-loader-path:
    - 
    # 指定使用模板的视图列表
    view-names:
    -  
    # 设定FreeMarker keys
    settings:
      key1: value1