# 没有在项目中定义的配置,可以直接在项目中使用@Value("${config}")注入到变量中
# 双引号包裹的值不会自动转义,即下面的值在输出时会 test 换行
test: "test \n"
# 单引号包裹的值会自动转义,即下面的值在输出时仍为test \n
test1: 'test \n'
# 可以使用random中的方法,properties和yml中都可以使用
uuid: ${random.uuid}
# 随机一个整数
num: ${random.int}
# 指定随机整数,范围在100到10000
num1: ${random.int[100,10000]}
# 10以内的随机整数
num2: ${random.int(10)}

config:
  user-id: 13
  placeholder: ${config.user-id}
  key-store: classpath:testssl.p12

spring:
  config:
    # 指定配置文件地址
    location: 