spring:
  groovy:
    template:
      # 指定HttpServletRequest的属性是否可以覆盖controller的model的同名项
      allow-request-override: false
      # 指定HttpSession的属性是否可以覆盖controller的model的同名项
      allow-session-override: false
      cache: false
      # 指定Template编码
      charset: UTF-8
      # 是否检查模板的路径是否存在
      check-template-location: false 
      configuration:
        # 是否在渲染模板时自动排查model的变量,默认为false
        auto-escape: false
        # 是否在渲染模板时自动缩进,默认为false 
        auto-indent: false
        # 如果自动缩进启用的话,是使用SPACES还是TAB,默认为SPACES
        auto-indent-string: 
        # 渲染模板时是否要输出换行,默认为false
        auto-new-line: false
        # 指定template base class
        base-template-class: 
        # 是否要缓存模板,默认为true 
        cache-templates: true
        # 在写入declaration header时使用的编码
        declaration-encoding: 
        # 是使用<br/>这种形式,还是<br></br>这种展开模式,默认为false
        expand-empty-elements: false 
        # 指定template locale
        locale: 
        # 当启用自动换行时,换行的输出,默认为系统的line.separator属性的值
        new-line-string: 
        # 指定groovy的模板路径,默认为classpath:/templates/
        resource-loader-path: 
        # 指定属性要使用双引号还是单引号,默认为false
        use-double-quotes: false
      content-type: 
      # 是否开启groovy模板的支持
      enabled: false
      # 设定所有request的属性在merge到模板的时候,是否要都添加到model中
      expose-request-attributes: false
      # 设定所有request的属性在merge到模板的时候,是否要都添加到model中
      expose-session-attributes: false
      # 设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
      expose-spring-macro-helpers: false
      # 指定模板的前缀
      prefix: 
      # 指定RequestContext属性的名
      request-context-attribute: 
      # 指定模板的路径,默认为classpath:/templates/
      resource-loader-path: 
      # 指定模板的后缀
      suffix: 
      # 指定要使用模板的视图名称
      view-names:
      - 