spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dream_single_web?autoReconnect=true&useUnicode=true&useSSL=false&characterEncoding=UTF8&tinyInt1isBit=false&allowMultiQueries=true
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.dream.*.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
  
mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
    banner: false
    
    
dream:
  security:
    http-ignore-resources:
    - /login*
    - /logout*
    - /druid/**
    web-ignore-resources:
    - "/public/**"
    - "/webjars/**"
    - "/v2/**"
    - "/swagger**"
    - "/static/**"
    - "/resources/**"